### Find All Products Gateway
GET {{url-base}}/product-service/products
Authorization: Bearer {{admin-token}}

### Create Product Gateway
POST {{url-base}}/product-service/products
Authorization: Bearer {{$auth.token("microservices")}}
Content-Type: application/json

{
  "sku": "0002",
  "description": "Coca-Cola",
  "price": 2.47,
  "status": true
}

### Find All Orders Gateway
GET {{url-base}}/order-service/orders

### Create Order Gateway
POST {{url-base}}/order-service/orders
Content-Type: application/json

{
  "details" : [
    {
      "sku": "0001",
      "price": 14.47,
      "quantity": 3
    }
  ]
}

### Authorization
POST {{token-url}}
Content-Type: application/x-www-form-urlencoded

client_id=api-gateway
  &grant_type=password
  &username=admin
  &password={{password}}
  &client_secret=a4IU5AiI37f1kgGoR5rTqzNR7suEfllE
