version: "3.9"
services:
  ### Postgres database fro KeyCloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_KEYCLOAK}
      - POSTGRES_USER=${DB_KEYCLOAK_USER}
      - POSTGRES_PASSWORD=${DB_KEYCLOAK_PASS}
    ports:
      - ${DB_KEYCLOAK_PORT}:5432
    expose:
      - ${DB_KEYCLOAK_PORT}
    command: -p ${DB_KEYCLOAK_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  ###
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - ${KEYCLOAK_PORT}:8080
    expose:
      - ${KEYCLOAK_PORT}
    depends_on:
      - db-keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=db-keycloak
      - DB_DATABASE=${DB_KEYCLOAK}
      - DB_PORT=${DB_KEYCLOAK_PORT}
      - DB_USER=${DB_KEYCLOAK_USER}
      - DB_PASSWORD=${DB_KEYCLOAK_PASS}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASS}

volumes:
  pgdata:
