version: "3.9"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      db-keycloak:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-keycloak
      KC_DB_USERNAME: ${DB_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASS}
      KC_DB_URL_PORT: ${DB_KEYCLOAK_PORT}
      KC_DB_URL_DATABASE: ${DB_KEYCLOAK}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}

  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${DB_KEYCLOAK}
      POSTGRES_USER: ${DB_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASS}
    healthcheck:
      test: "exit 0"
    ports:
      - ${DB_KEYCLOAK_PORT}:5432
    command: -p ${DB_KEYCLOAK_PORT}
    volumes:
      - keycloakdata:/var/lib/postgresql/data

  product-service:
    image: postgres:15.2
    container_name: product-service
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_PRODUCTS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PRODUCTS}
      POSTGRES_DB: ${DB_NAME_PRODUCTS}
    volumes:
      - products:/var/lib/postgresql/data

  order-service:
    image: postgres:15.2
    container_name: order-service
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_PRODUCTS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PRODUCTS}
      POSTGRES_DB: ${DB_NAME_PRODUCTS}
    volumes:
      - orders:/var/lib/postgresql/data

  inventory-service:
    image: postgres:15.2
    container_name: inventory-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_PRODUCTS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PRODUCTS}
      POSTGRES_DB: ${DB_NAME_PRODUCTS}
    volumes:
      - inventories:/var/lib/postgresql/data

volumes:
  products:
  orders:
  inventories:
  keycloakdata:
