version: "3.9"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      db-keycloak:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-keycloak
      KC_DB_USERNAME: ${DB_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DB_KEYCLOAK_PASS}
      KC_DB_URL_PORT: ${DB_KEYCLOAK_PORT}
      KC_DB_URL_DATABASE: ${DB_KEYCLOAK}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}

  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${DB_KEYCLOAK}
      POSTGRES_USER: ${DB_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASS}
    healthcheck:
      test: "exit 0"
    ports:
      - ${DB_KEYCLOAK_PORT}:5432
    command: -p ${DB_KEYCLOAK_PORT}
    volumes:
      - keycloakdata:/var/lib/postgresql/data

  psqldata:
    image: postgres:15.2
    container_name: psqldata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME_AUTH}
      - POSTGRES_PASSWORD=${DB_PASSWORD_AUTH}
      - POSTGRES_DB=${DB_NAME_AUTH}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  keycloakdata:
