spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
      default-filters:
        - SaveSession
        - TokenRelay

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/microservices-realm
        registration:
          keycloak:
            provider: keycloak
            scope: openid
            client-id: api-gateway
            client-secret: a4IU5AiI37f1kgGoR5rTqzNR7suEfllE
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8099/login/oauth2/code/keycloak


eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}${server.servlet.context-path}

server:
  port: 8099
