### Create Order
POST http://localhost:8101/order-service/orders
Content-Type: application/json

{
  "details" : [
    {
      "sku": "0001",
      "price": 23.87,
      "quantity": 3
    }
  ]
}

### Find All Orders
GET http://localhost:8101/order-service/orders